CREATE DATABASE march2015_likes; 
use march2015_likes;
CREATE TABLE users (id INT UNSIGNED NOT NULL AUTO_INCREMENT, first_name CHAR(20) NOT NULL, last_name CHAR(20) NOT NULL, birth_date DATE, PRIMARY KEY (id));
CREATE TABLE friendships (id_user1 INT UNSIGNED NOT NULL, id_user2 INT UNSIGNED NOT NULL, date_time TIMESTAMP NOT NULL, INDEX(id_user1), INDEX(id_user2), FOREIGN KEY (id_user1) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE, FOREIGN KEY (id_user2) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE posts (id INT UNSIGNED NOT NULL AUTO_INCREMENT, id_user INT UNSIGNED NOT NULL, text CHAR(250) NOT NULL, date_time TIMESTAMP NOT NULL, PRIMARY KEY (id), INDEX(id_user), FOREIGN KEY (id_user) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE);
CREATE TABLE likes (id_post INT UNSIGNED NOT NULL, id_user INT UNSIGNED NOT NULL, date_time TIMESTAMP NOT NULL, INDEX(id_post), INDEX(id_user), FOREIGN KEY (id_post) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE, FOREIGN KEY (id_user) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE);
